[package]
name = "stateless-validator-reth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bumpalo.workspace = true
bytes.workspace = true
once_cell.workspace = true
smallvec.workspace = true
thiserror.workspace = true

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-genesis = { workspace = true, features = ["serde-bincode-compat"] }
alloy-primitives = { workspace = true, features = ["map-foldhash", "map-indexmap"] }
alloy-rlp.workspace = true
alloy-rpc-types-debug.workspace = true
alloy-rpc-types-engine = { workspace = true, features = ["serde"] }
alloy-trie.workspace = true

# revm
revm.workspace = true

# reth
reth-chainspec.workspace = true
reth-ethereum-primitives.workspace = true
reth-evm-ethereum.workspace = true
reth-payload-validator.workspace = true
reth-primitives-traits.workspace = true
reth-stateless.workspace = true
reth-trie-common.workspace = true
reth-tries.workspace = true

# zkvm-standard
zkvm-interface = { workspace = true, optional = true }

# ere
ere-platform-core.workspace = true

# local
stateless-validator-common.workspace = true

[dev-dependencies]
paste.workspace = true
ere-dockerized.workspace = true
stateless-validator-test.workspace = true

[[test]]
name = "host_execution"
required-features = ["host"]

[features]
# guest
default = ["std"]
std = ["once_cell/std", "stateless-validator-common/std"]
openvm = ["zkvm-interface"]
sp1 = ["zkvm-interface"]
zisk = ["zkvm-interface"]
zkvm-interface = ["alloy-consensus/crypto-backend", "dep:zkvm-interface"]

# host
host = ["std", "stateless-validator-common/host"]
